server.port=9090

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database configuration
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6541/shareit
spring.datasource.username=shareit
spring.datasource.password=shareit

# Logging configuration
logging.level.org.springframework.validation=DEBUG
logging.level.org.hibernate.validator=DEBUG
logging.level.ru.practicum.shareit.user.controller=DEBUG
logging.level.ru.practicum.shareit.user=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
